from .auth import auth_router
from .schools import schools_router
from .users import users_router
from .students import students_router
from .academic import academic_router
from .attendance import attendance_router
from .grades import grades_router
from .dashboard import dashboard_router
from .communication import communication_router
